// Авто-извлечено из jar Forestry + Binnie ExtraBees (ragu.html не трогается).
const BEES = [
  { id:"Обычная", source:"Forestry", parents:[["дикая пчела (из улья)", "дикая пчела (из улья)", 15]], products:[["Медовые соты", 0.35, "product"]] },
  { id:"Развитая", source:"Forestry", parents:[["Обычная", "дикая пчела (из улья)", 12]], products:[["Медовые соты", 0.4, "product"]] },
  { id:"Знатная", source:"Forestry", parents:[["Обычная", "Развитая", 10]], products:[["Капающие соты", 0.2, "product"]] },
  { id:"Величавая", source:"Forestry", parents:[["Знатная", "Развитая", 8]], products:[["Капающие соты", 0.3, "product"]] },
  { id:"Имперская", source:"Forestry", parents:[["Знатная", "Величавая", 8]], products:[["Капающие соты", 0.2, "product"], ["Маточное молочко", 0.15, "product"]] },
  { id:"Прилежная", source:"Forestry", parents:[["Обычная", "Развитая", 10]], products:[["Вязкие соты", 0.2, "product"]] },
  { id:"Неутомимая", source:"Forestry", parents:[["Прилежная", "Развитая", 8]], products:[["Вязкие соты", 0.3, "product"]] },
  { id:"Трудолюбивая", source:"Forestry", parents:[["Прилежная", "Неутомимая", 8]], products:[["Вязкие соты", 0.2, "product"], ["Комок пыльцы", 0.15, "product"]] },
  { id:"Героическая", source:"Forestry", parents:[["Стойкая", "Доблестная", 6]], products:[["Какао-соты", 0.4, "product"]] },
  { id:"Зловещая", source:"Forestry", parents:[["Развитая", "особый вид (задаётся конфигом)", 60]], products:[["Кипящие соты", 0.45, "product"]] },
  { id:"Жестокая", source:"Forestry", parents:[["Зловещая", "особый вид (задаётся конфигом)", 40]], products:[["Кипящие соты", 0.55, "product"], ["Зола", 0.15, "product"]] },
  { id:"Одержимая", source:"Forestry", parents:[["Зловещая", "Жестокая", 25]], products:[["Кипящие соты", 0.45, "product"], ["Светящаяся пыль", 0.15, "product"]] },
  { id:"Бережливая", source:"Forestry", parents:[["Скромная", "Зловещая", 16], ["Скромная", "Жестокая", 10]], products:[["Пересохшие соты", 0.3, "product"]] },
  { id:"Суровая", source:"Forestry", parents:[["Скромная", "Бережливая", 8]], products:[["Пересохшие соты", 0.2, "product"], ["Рыхлые соты", 0.5, "specialty"]] },
  { id:"Редкая", source:"Forestry", parents:[["Суровая", "Тропическая", 12]], products:[["Шелковистые соты", 0.3, "product"]] },
  { id:"Райская", source:"Forestry", parents:[["Редкая", "Тропическая", 8]], products:[["Шелковистые соты", 0.2, "product"]] },
  { id:"Призрачная", source:"Forestry", parents:[["Уединённая", "Драконья", 4]], products:[["Таинственные соты", 0.5, "product"]] },
  { id:"Воображаемая", source:"Forestry", parents:[["Призрачная", "Драконья", 2]], products:[["Таинственные соты", 0.4, "product"]] },
  { id:"Ледяная", source:"Forestry", parents:[["Трудолюбивая", "Зимняя", 12]], products:[["Морозные соты", 0.2, "product"], ["Осколок льда", 0.2, "product"]] },
  { id:"Ледниковая", source:"Forestry", parents:[["Ледяная", "Зимняя", 8]], products:[["Морозные соты", 0.2, "product"], ["Осколок льда", 0.4, "product"]] },
  { id:"Карательная", source:"Forestry", parents:[["Монашья", "Одержимая", 4]], products:[["Облучённые соты", 0.25, "product"]] },
  { id:"Мстительная", source:"Forestry", parents:[["Одержимая", "Карательная", 8], ["Монашья", "Карательная", 8]], products:[["Облучённые соты", 0.4, "product"]] },
  { id:"Мстящая", source:"Forestry", parents:[["Мстительная", "Карательная", 4]], products:[["Облучённые соты", 0.4, "product"]] },
  { id:"Заячья", source:"Forestry", parents:[["Луговая", "Лесная", 10]], products:[["Шелковистые соты", 0.3, "product"], ["Яйцо", 0.1, "product"]] },
  { id:"Весёлая", source:"Forestry", parents:[["Зимняя", "Лесная", 10]], products:[["Морозные соты", 0.3, "product"], ["Осколок льда", 0.2, "product"]] },
  { id:"Пьяная", source:"Forestry", parents:[["Зимняя", "Луговая", 10]], products:[["Морозные соты", 0.3, "product"], ["Осколок льда", 0.2, "product"]] },
  { id:"Хитрая", source:"Forestry", parents:[["Зловещая", "Обычная", 10]], products:[["Медовые соты", 0.4, "product"], ["Печенье", 0.15, "product"], ["Череп скелета", 0.02, "specialty"], ["Голова зомби", 0.02, "specialty"], ["Голова игрока", 0.02, "specialty"], ["Голова крипера", 0.02, "specialty"]] },
  { id:"Сельская", source:"Forestry", parents:[["Луговая", "Прилежная", 12]], products:[["Пшеничные соты", 0.2, "product"]] },
  { id:"Прошлая", source:"Forestry", parents:[["Сельская", "Неутомимая", 10]], products:[["Пшеничные соты", 0.27, "product"]] },
  { id:"Земельная", source:"Forestry", parents:[["Прошлая", "Трудолюбивая", 6]], products:[["Пшеничные соты", 0.35, "product"]] },
  { id:"Топкая", source:"Forestry", parents:[["Болотная", "Знатная", 15]], products:[["Замшелые соты", 0.36, "product"]] },
  { id:"Болотистая", source:"Forestry", parents:[["Болотная", "Топкая", 9]], products:[["Замшелые соты", 0.39, "product"], ["Торф", 0.08, "specialty"]] },
  { id:"Укромная", source:"Forestry", parents:[["Монашья", "Суровая", 12]], products:[["Спелые соты", 0.2, "specialty"]] },
  { id:"Уединённая", source:"Forestry", parents:[["Монашья", "Укромная", 8]], products:[["Спелые соты", 0.2, "specialty"]] },
  { id:"Засушливая", source:"ExtraBees", parents:[["Луговая", "Бережливая", 10], ["Лесная", "Бережливая", 10]], products:[["Бесплодные соты", 0.3, "product"]] },
  { id:"Бесплодная", source:"ExtraBees", parents:[["Обычная", "Засушливая", 10]], products:[["Бесплодные соты", 0.3, "product"]] },
  { id:"Заброшенная", source:"ExtraBees", parents:[["Засушливая", "Бесплодная", 10]], products:[["Бесплодные соты", 0.3, "product"]] },
  { id:"Разлагающаяся", source:"ExtraBees", parents:[["Болотная", "Бесплодная", 15]], products:[["Бесплодные соты", 0.3, "product"], ["Разлагающиеся соты", 0.08, "specialty"]] },
  { id:"Мучительная", source:"ExtraBees", parents:[["Лесная", "Бесплодная", 15]], products:[["Бесплодные соты", 0.25, "product"], ["Пыльные соты", 0.25, "specialty"]] },
  { id:"Гнилая", source:"ExtraBees", parents:[["Луговая", "Заброшенная", 15]], products:[["Бесплодные соты", 0.3, "product"], ["Гнилые соты", 0.1, "specialty"]] },
  { id:"Скелетная", source:"ExtraBees", parents:[["Лесная", "Заброшенная", 15]], products:[["Бесплодные соты", 0.3, "product"], ["Костяные соты", 0.1, "specialty"]] },
  { id:"Криперная", source:"ExtraBees", parents:[["Скромная", "Заброшенная", 15]], products:[["Бесплодные соты", 0.3, "product"], ["Рыхлые соты", 0.08, "specialty"]] },
  { id:"Толерантная", source:"ExtraBees", parents:[["Прилежная", "Каменная", 12]], products:[["Каменистые соты", 0.3, "product"]] },
  { id:"Выносливая", source:"ExtraBees", parents:[["Неутомимая", "Толерантная", 10]], products:[["Каменистые соты", 0.3, "product"]] },
  { id:"Устойчивая", source:"ExtraBees", parents:[["Трудолюбивая", "Выносливая", 6]], products:[["Каменистые соты", 0.3, "product"]] },
  { id:"Коррозийная", source:"ExtraBees", parents:[["Зимняя", "Устойчивая", 5], ["Скромная", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Медные соты", 0.06, "specialty"]] },
  { id:"Потускневшая", source:"ExtraBees", parents:[["Болотная", "Устойчивая", 5], ["Тропическая", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Оловянные соты", 0.06, "specialty"]] },
  { id:"Ржавая", source:"ExtraBees", parents:[["Луговая", "Устойчивая", 5], ["Лесная", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Железные соты", 0.05, "specialty"]] },
  { id:"Свинцовая", source:"ExtraBees", parents:[["Луговая", "Устойчивая", 5], ["Скромная", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Свинцовые соты", 0.05, "specialty"]] },
  { id:"Оцинкованная", source:"ExtraBees", parents:[["Зимняя", "Устойчивая", 5], ["Тропическая", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Цинковые соты", 0.05, "specialty"]] },
  { id:"Неприступная", source:"ExtraBees", parents:[["Развитая", "Устойчивая", 3]], products:[["Каменистые соты", 0.2, "product"], ["Титановые соты", 0.02, "specialty"]] },
  { id:"Непобедимая", source:"ExtraBees", parents:[["Обычная", "Устойчивая", 3]], products:[["Каменистые соты", 0.2, "product"], ["Вольфрамовые соты", 0.01, "specialty"]] },
  { id:"Взволнованная", source:"ExtraBees", parents:[["Лесная", "Устойчивая", 5], ["Болотная", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Никелевые соты", 0.05, "specialty"]] },
  { id:"Сверкающая", source:"ExtraBees", parents:[["Величавая", "Ржавая", 2], ["Величавая", "Коррозийная", 2], ["Величавая", "Взволнованная", 2], ["Величавая", "Непобедимая", 2]], products:[["Каменистые соты", 0.2, "product"], ["Золотые соты", 0.02, "specialty"]] },
  { id:"Сияющая", source:"ExtraBees", parents:[["Величавая", "Оцинкованная", 2], ["Величавая", "Потускневшая", 2], ["Величавая", "Свинцовая", 2], ["Величавая", "Неприступная", 2]], products:[["Каменистые соты", 0.2, "product"], ["Серебряные соты", 0.02, "specialty"]] },
  { id:"Ценная", source:"ExtraBees", parents:[["Сверкающая", "Сияющая", 2]], products:[["Каменистые соты", 0.2, "product"], ["Платиновые соты", 0.01, "specialty"]] },
  { id:"Лазуритовая", source:"ExtraBees", parents:[["Имперская", "Устойчивая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Лазуритовые соты", 0.05, "specialty"]] },
  { id:"Изумрудная", source:"ExtraBees", parents:[["Лесная", "Лазуритовая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Изумрудные соты", 0.04, "specialty"]] },
  { id:"Рубиновая", source:"ExtraBees", parents:[["Скромная", "Лазуритовая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Рубиновые соты", 0.03, "specialty"]] },
  { id:"Сапфировая", source:"ExtraBees", parents:[["Водная", "Лазуритовая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Сапфировые соты", 0.03, "specialty"]] },
  { id:"Алмазная", source:"ExtraBees", parents:[["Развитая", "Лазуритовая", 5]], products:[["Каменистые соты", 0.2, "product"], ["Алмазные соты", 0.01, "specialty"]] },
  { id:"Нестабильная", source:"ExtraBees", parents:[["Доисторическая", "Устойчивая", 5]], products:[["Бесплодные соты", 0.2, "product"]] },
  { id:"Ядерная", source:"ExtraBees", parents:[["Нестабильная", "Ржавая", 5], ["Нестабильная", "Коррозийная", 5], ["Нестабильная", "Потускневшая", 5], ["Нестабильная", "Оцинкованная", 5], ["Нестабильная", "Взволнованная", 5], ["Нестабильная", "Свинцовая", 5]], products:[["Бесплодные соты", 0.2, "product"]] },
  { id:"Радиоактивная", source:"ExtraBees", parents:[["Ядерная", "Сверкающая", 5], ["Ядерная", "Сияющая", 5]], products:[["Бесплодные соты", 0.2, "product"], ["Урановые соты", 0.02, "specialty"]] },
  { id:"Йеллориумовая", source:"ExtraBees", parents:[["Бережливая", "Ядерная", 5]], products:[["Бесплодные соты", 0.2, "product"], ["Йеллориумовые соты", 0.02, "specialty"]] },
  { id:"Цианитовая", source:"ExtraBees", parents:[["Ядерная", "Йеллориумовая", 5]], products:[["Бесплодные соты", 0.2, "product"], ["Кианитовые соты", 0.01, "specialty"]] },
  { id:"Блутониевая", source:"ExtraBees", parents:[["Цианитовая", "Йеллориумовая", 5]], products:[["Бесплодные соты", 0.2, "product"], ["Блутониевые соты", 0.01, "specialty"]] },
  { id:"Древняя", source:"ExtraBees", parents:[["Знатная", "Прилежная", 10]], products:[["Древние соты", 0.3, "product"]] },
  { id:"Первобытная", source:"ExtraBees", parents:[["Укромная", "Древняя", 8]], products:[["Древние соты", 0.3, "product"]] },
  { id:"Доисторическая", source:"ExtraBees", parents:[["Первобытная", "Древняя", 8]], products:[["Древние соты", 0.3, "product"]] },
  { id:"Реликтовая", source:"ExtraBees", parents:[["Имперская", "Доисторическая", 8]], products:[["Древние соты", 0.3, "product"]] },
  { id:"Окаменелая", source:"ExtraBees", parents:[["Первобытная", "Прорастающая", 8], ["Сельская", "Первобытная", 8]], products:[["Древние соты", 0.2, "product"], ["Окаменевшие соты", 0.08, "specialty"]] },
  { id:"Смолистая", source:"ExtraBees", parents:[["Топкая", "Первобытная", 8]], products:[["Древние соты", 0.2, "product"], ["Янтарные соты", 0.05, "specialty"]] },
  { id:"Нефтяная", source:"ExtraBees", parents:[["Океаническая", "Первобытная", 8], ["Бережливая", "Первобытная", 8]], products:[["Древние соты", 0.2, "product"], ["Масляные соты", 0.05, "specialty"]] },
  { id:"Дистиллированная", source:"ExtraBees", parents:[["Трудолюбивая", "Нефтяная", 8]], products:[["Древние соты", 0.1, "product"]] },
  { id:"Изысканная", source:"ExtraBees", parents:[["Дистиллированная", "Нефтяная", 8]], products:[["Масляные соты", 0.1, "product"], ["Нефтяные соты", 0.04, "specialty"]] },
  { id:"Медлительная", source:"ExtraBees", parents:[["Дистиллированная", "Окаменелая", 8]], products:[["Окаменевшие соты", 0.1, "product"], ["Смолистые соты", 0.3, "specialty"]] },
  { id:"Эластичная", source:"ExtraBees", parents:[["Дистиллированная", "Смолистая", 8]], products:[["Янтарные соты", 0.1, "product"], ["Каучуковые соты", 0.05, "specialty"]] },
  { id:"Речная", source:"ExtraBees", parents:[["Прилежная", "Водная", 10]], products:[["Влажные соты", 0.3, "product"], ["Глиняные соты", 0.2, "specialty"]] },
  { id:"Океаническая", source:"ExtraBees", parents:[["Прилежная", "Водная", 10]], products:[["Влажные соты", 0.3, "product"]] },
  { id:"Испачканная", source:"ExtraBees", parents:[["Черномазая", "Океаническая", 8], ["Лесная", "Прилежная", 10], ["Прошлая", "Луговая", 10], ["Неутомимая", "Прорастающая", 10], ["Трудолюбивая", "Процветающая", 8]], products:[["Влажные соты", 0.3, "product"], ["Краситель", 0.1, "specialty"], ["Медовые соты", 0.35, "product"], ["Пшеничные соты", 0.3, "product"], ["Семянные соты", 0.1, "specialty"]] },
  { id:"Сладкая", source:"ExtraBees", parents:[["Доблестная", "Прилежная", 15]], products:[["Медовые соты", 0.4, "product"], ["Сахар", 0.1, "product"]] },
  { id:"Сахарная", source:"ExtraBees", parents:[["Сельская", "Сладкая", 15]], products:[["Медовые соты", 0.4, "product"], ["Сахар", 0.2, "product"]] },
  { id:"Созревающая", source:"ExtraBees", parents:[["Сладкая", "Прорастающая", 5]], products:[["Медовые соты", 0.3, "product"], ["Сахар", 0.1, "product"], ["Фруктовые соты", 0.1, "specialty"]] },
  { id:"Фруктовая", source:"ExtraBees", parents:[["Сладкая", "Процветающая", 5]], products:[["Медовые соты", 0.3, "product"], ["Сахар", 0.15, "product"], ["Фруктовые соты", 0.2, "specialty"]] },
  { id:"Ферментная", source:"ExtraBees", parents:[["Прошлая", "Луговая", 10]], products:[["Пшеничные соты", 0.3, "product"], ["Спиртовые соты", 0.1, "specialty"]] },
  { id:"Коровья", source:"ExtraBees", parents:[["Прошлая", "Водная", 10]], products:[["Пшеничные соты", 0.3, "product"], ["Молочные соты", 0.1, "specialty"]] },
  { id:"Кофейная", source:"ExtraBees", parents:[["Прошлая", "Тропическая", 10], ["Топкая", "Водная", 10], ["Болотистая", "Влажная", 8], ["Болотистая", "Топкая", 8], ["Болотистая", "Грибная", 8]], products:[["Пшеничные соты", 0.3, "product"], ["Кофейные соты", 0.08, "specialty"], ["Замшелые соты", 0.3, "product"], ["Грибные соты", 0.15, "specialty"]] },
  { id:"Яростная", source:"ExtraBees", parents:[["Жестокая", "Озлобленная", 30]], products:[["Кипящие соты", 0.25, "product"]] },
  { id:"Огнедышащая", source:"ExtraBees", parents:[["Одержимая", "Яростная", 20]], products:[["Кипящие соты", 0.25, "product"], ["Горящие соты", 0.1, "specialty"]] },
  { id:"Сердитая", source:"ExtraBees", parents:[["Яростная", "Возбуждённая", 5]], products:[["Пылающие соты", 0.15, "product"]] },
  { id:"Вредоносная", source:"ExtraBees", parents:[["Зловещая", "Тропическая", 10]], products:[["Шелковистые соты", 0.25, "product"]] },
  { id:"Заразная", source:"ExtraBees", parents:[["Тропическая", "Вредоносная", 8]], products:[["Шелковистые соты", 0.25, "product"]] },
  { id:"Ядовитая", source:"ExtraBees", parents:[["Вредоносная", "Заразная", 8]], products:[["Шелковистые соты", 0.25, "product"], ["Ядовитые соты", 0.12, "specialty"]] },
  { id:"Вязкая", source:"ExtraBees", parents:[["Редкая", "Водная", 10]], products:[["Шелковистые соты", 0.25, "product"]] },
  { id:"Клейкая", source:"ExtraBees", parents:[["Редкая", "Вязкая", 8]], products:[["Шелковистые соты", 0.25, "product"]] },
  { id:"Липкая", source:"ExtraBees", parents:[["Вязкая", "Клейкая", 8]], products:[["Шелковистые соты", 0.25, "product"], ["Слизистые соты", 0.12, "specialty"]] },
  { id:"Едкая", source:"ExtraBees", parents:[["Вредоносная", "Вязкая", 10]], products:[["Шелковистые соты", 0.2, "product"]] },
  { id:"Едко-щелочная", source:"ExtraBees", parents:[["Жестокая", "Едкая", 8]], products:[["Шелковистые соты", 0.25, "product"], ["Серные соты", 0.03, "specialty"]] },
  { id:"Едко-кислотная", source:"ExtraBees", parents:[["Едкая", "Едко-щелочная", 4]], products:[["Шелковистые соты", 0.2, "product"], ["Серные соты", 0.16, "specialty"]] },
  { id:"Возбуждённая", source:"ExtraBees", parents:[["Доблестная", "Развитая", 10]], products:[["Энергетические соты", 0.1, "product"]] },
  { id:"Энергетическая", source:"ExtraBees", parents:[["Прилежная", "Возбуждённая", 8]], products:[["Энергетические соты", 0.12, "product"]] },
  { id:"Исступлённая", source:"ExtraBees", parents:[["Возбуждённая", "Энергетическая", 8], ["Зимняя", "Прилежная", 10], ["Океаническая", "Бесстрастная", 10]], products:[["Энергетические соты", 0.2, "product"], ["Статические соты", 0.08, "specialty"], ["Морозные соты", 0.25, "product"], ["Морозные соты", 0.2, "product"], ["Ледяные соты", 0.1, "specialty"]] },
  { id:"Омрачённая", source:"ExtraBees", parents:[["Зловещая", "Каменная", 10]], products:[["Теневые соты", 0.05, "product"]] },
  { id:"Потемневшая", source:"ExtraBees", parents:[["Омрачённая", "Каменная", 8]], products:[["Теневые соты", 0.1, "product"]] },
  { id:"Глубинная", source:"ExtraBees", parents:[["Омрачённая", "Потемневшая", 8]], products:[["Теневые соты", 0.25, "product"]] },
  { id:"Тёмно-бордовая", source:"ExtraBees", parents:[["Лесная", "Доблестная", 5]], products:[["Медовые соты", 0.75, "product"], ["Красные окрашенные соты", 0.25, "specialty"]] },
  { id:"Шафрановая", source:"ExtraBees", parents:[["Луговая", "Доблестная", 5]], products:[["Медовые соты", 0.75, "product"], ["Жёлтые окрашенные соты", 0.25, "specialty"]] },
  { id:"Прусская", source:"ExtraBees", parents:[["Доблестная", "Водная", 5]], products:[["Медовые соты", 0.75, "product"], ["Синие окрашенные соты", 0.25, "specialty"]] },
  { id:"Зелёная", source:"ExtraBees", parents:[["Тропическая", "Доблестная", 5]], products:[["Медовые соты", 0.75, "product"], ["Зелёные окрашенные соты", 0.25, "specialty"]] },
  { id:"Черномазая", source:"ExtraBees", parents:[["Доблестная", "Каменная", 5]], products:[["Медовые соты", 0.75, "product"], ["Чёрные окрашенные соты", 0.25, "specialty"]] },
  { id:"Отбелённая", source:"ExtraBees", parents:[["Зимняя", "Доблестная", 5]], products:[["Медовые соты", 0.75, "product"], ["Белые окрашенные соты", 0.25, "specialty"]] },
  { id:"Коричневая", source:"ExtraBees", parents:[["Болотная", "Доблестная", 5]], products:[["Медовые соты", 0.75, "product"], ["Коричневые окрашенные соты", 0.25, "specialty"]] },
  { id:"Оранжевая", source:"ExtraBees", parents:[["Тёмно-бордовая", "Шафрановая", 5]], products:[["Медовые соты", 0.75, "product"], ["Оранжевые окрашенные соты", 0.25, "specialty"]] },
  { id:"Бирюзовая", source:"ExtraBees", parents:[["Зелёная", "Прусская", 5]], products:[["Медовые соты", 0.75, "product"], ["Бирюзовые окрашенные соты", 0.25, "specialty"]] },
  { id:"Фиолетовая", source:"ExtraBees", parents:[["Тёмно-бордовая", "Прусская", 5]], products:[["Медовые соты", 0.75, "product"], ["Фиолетовые окрашенные соты", 0.25, "specialty"]] },
  { id:"Серая", source:"ExtraBees", parents:[["Черномазая", "Отбелённая", 5]], products:[["Медовые соты", 0.75, "product"], ["Серые окрашенные соты", 0.25, "specialty"]] },
  { id:"Голубая", source:"ExtraBees", parents:[["Прусская", "Отбелённая", 5]], products:[["Медовые соты", 0.75, "product"], ["Светло-голубые окрашенные соты", 0.25, "specialty"]] },
  { id:"Розовая", source:"ExtraBees", parents:[["Тёмно-бордовая", "Отбелённая", 5]], products:[["Медовые соты", 0.75, "product"], ["Розовые окрашенные соты", 0.25, "specialty"]] },
  { id:"Лаймовая", source:"ExtraBees", parents:[["Зелёная", "Отбелённая", 5]], products:[["Медовые соты", 0.75, "product"], ["Лаймовые окрашенные соты", 0.25, "specialty"]] },
  { id:"Пурпурная", source:"ExtraBees", parents:[["Фиолетовая", "Розовая", 5]], products:[["Медовые соты", 0.75, "product"], ["Пурпурные окрашенные соты", 0.25, "specialty"]] },
  { id:"Светло-серая", source:"ExtraBees", parents:[["Серая", "Отбелённая", 5], ["Суровая", "Возбуждённая", 5]], products:[["Медовые соты", 0.75, "product"], ["Светло-серые окрашенные соты", 0.25, "specialty"]] },
  { id:"Изнурённая", source:"ExtraBees", parents:[["Драконья", "Реликтовая", 2], ["Суровая", "Заброшенная", 5]], products:[["Медовые соты", 0.3, "product"], ["Пыльца", 0.2, "specialty"], ["Фиолетовые окрашенные соты", 0.15, "specialty"], ["Нестабильные соты", 0.12, "product"]] },
  { id:"Квантовая", source:"ExtraBees", parents:[["Призрачная", "Пространственная", 5]], products:[["Кварцевые соты", 0.25, "product"], ["Уверенные соты", 0.15, "specialty"], ["Мерцающие соты", 0.15, "specialty"]] },
  { id:"Аномальная", source:"ExtraBees", parents:[["Укромная", "Драконья", 5]], products:[["Кварцевые соты", 0.25, "product"]] },
  { id:"Пространственная", source:"ExtraBees", parents:[["Уединённая", "Аномальная", 5]], products:[["Кварцевые соты", 0.25, "product"], ["Уверенные соты", 0.05, "specialty"]] },
  { id:"Мистическая", source:"ExtraBees", parents:[["Знатная", "Монашья", 5]], products:[] },
  { id:"Лесная", source:"Forestry", parents:[], products:[["Медовые соты", 0.3, "product"]] },
  { id:"Луговая", source:"Forestry", parents:[], products:[["Медовые соты", 0.3, "product"]] },
  { id:"Стойкая", source:"Forestry", parents:[], products:[["Какао-соты", 0.2, "product"]] },
  { id:"Доблестная", source:"Forestry", parents:[], products:[["Какао-соты", 0.3, "product"], ["Сахар", 0.15, "specialty"]] },
  { id:"Скромная", source:"Forestry", parents:[], products:[["Пересохшие соты", 0.2, "product"]] },
  { id:"Тропическая", source:"Forestry", parents:[], products:[["Шелковистые соты", 0.2, "product"]] },
  { id:"Драконья", source:"Forestry", parents:[], products:[["Таинственные соты", 0.3, "product"]] },
  { id:"Зимняя", source:"Forestry", parents:[], products:[["Морозные соты", 0.3, "product"]] },
  { id:"Болотная", source:"Forestry", parents:[], products:[["Замшелые соты", 0.3, "product"]] },
  { id:"Монашья", source:"Forestry", parents:[], products:[["Пшеничные соты", 0.3, "product"], ["Спелые соты", 0.1, "specialty"]] },
  { id:"Каменная", source:"ExtraBees", parents:[], products:[["Каменистые соты", 0.3, "product"]] },
  { id:"Водная", source:"ExtraBees", parents:[], products:[["Влажные соты", 0.3, "product"]] },
  { id:"Озлобленная", source:"ExtraBees", parents:[], products:[["Кипящие соты", 0.25, "product"]] },
];