// Авто-извлечено из jar Forestry + Binnie ExtraTrees (ragu.html НЕ редактируется).
// id = результат; parents=[[p1,p2]]; chance — базовый шанс (%). Имена русские из lang.
const RECIPES = [
  { id:"липы пушистой", parents:[["белой берёзы", "яблочного дуба"]], chance:15, source:"Forestry" },
  { id:"обычного орехового дерева", parents:[["липы пушистой", "сакуры"]], chance:10, source:"Forestry" },
  { id:"каштана посевного", parents:[["обычного орехового дерева", "липы пушистой"]], chance:10, source:"Forestry" },
  { id:"каштана посевного", parents:[["обычного орехового дерева", "сакуры"]], chance:10, source:"Forestry" },
  { id:"сакуры", parents:[["липы пушистой", "яблочного дуба"]], chance:10, source:"Forestry" },
  { id:"сакуры", parents:[["липы пушистой", "белой берёзы"]], chance:10, source:"Forestry" },
  { id:"лимонного дерева", parents:[["липы пушистой", "сакуры"]], chance:5, source:"Forestry" },
  { id:"сливового дерева", parents:[["лимонного дерева", "сакуры"]], chance:5, source:"Forestry" },
  { id:"сахарного клёна", parents:[["красной ели", "мировой лиственницы"]], chance:5, source:"Forestry" },
  { id:"мировой лиственницы", parents:[["красной ели", "белой берёзы"]], chance:10, source:"Forestry" },
  { id:"мировой лиственницы", parents:[["красной ели", "яблочного дуба"]], chance:10, source:"Forestry" },
  { id:"жёлтой сосны", parents:[["красной ели", "мировой лиственницы"]], chance:10, source:"Forestry" },
  { id:"береговой секвойи", parents:[["мировой лиственницы", "жёлтой сосны"]], chance:5, source:"Forestry" },
  { id:"тикового дерева", parents:[["тёмного дуба", "дерева джунглей"]], chance:10, source:"Forestry" },
  { id:"муравьиного дерева", parents:[["тикового дерева", "тёмного дуба"]], chance:10, source:"Forestry" },
  { id:"хлопкового дерева", parents:[["дерева джунглей", "тикового дерева"]], chance:10, source:"Forestry" },
  { id:"мирта", parents:[["тёмного дуба", "хлопкового дерева"]], chance:10, source:"Forestry" },
  { id:"зебрано", parents:[["мирта", "белого тополя"]], chance:5, source:"Forestry" },
  { id:"жёлтого меранти", parents:[["хлопкового дерева", "мирта"]], chance:10, source:"Forestry" },
  { id:"пустынной акации", parents:[["тикового дерева", "бальзы"]], chance:10, source:"Forestry" },
  { id:"падука", parents:[["акации", "дерева джунглей"]], chance:10, source:"Forestry" },
  { id:"бальзы", parents:[["тикового дерева", "акации"]], chance:10, source:"Forestry" },
  { id:"кокоболо", parents:[["пустынной акации", "тёмного дуба"]], chance:10, source:"Forestry" },
  { id:"дерева Венге", parents:[["кокоболо", "бальзы"]], chance:10, source:"Forestry" },
  { id:"Адансонии Грандидье", parents:[["бальзы", "дерева Венге"]], chance:10, source:"Forestry" },
  { id:"синего гибискуса", parents:[["бальзы", "пустынной акации"]], chance:5, source:"Forestry" },
  { id:"белой ивы", parents:[["яблочного дуба", "белой берёзы"]], chance:10, source:"Forestry", cond:"температура: WARM–HOT, влажность: DAMP" },
  { id:"белой ивы", parents:[["яблочного дуба", "липы пушистой"]], chance:10, source:"Forestry", cond:"температура: WARM–HOT, влажность: DAMP" },
  { id:"белой ивы", parents:[["липы пушистой", "белой берёзы"]], chance:10, source:"Forestry", cond:"температура: WARM–HOT, влажность: DAMP" },
  { id:"Сипири", parents:[["хлопкового дерева", "жёлтого меранти"]], chance:10, source:"Forestry", cond:"температура: WARM–HOT, влажность: DAMP" },
  { id:"дынного дерева", parents:[["дерева джунглей", "сакуры"]], chance:5, source:"Forestry" },
  { id:"финиковой пальмы", parents:[["дерева джунглей", "дынного дерева"]], chance:5, source:"Forestry" },
  { id:"белого тополя", parents:[["белой берёзы", "белой ивы"]], chance:5, source:"Forestry" },
  { id:"белого тополя", parents:[["яблочного дуба", "белой ивы"]], chance:5, source:"Forestry" },
  { id:"белого тополя", parents:[["липы пушистой", "белой ивы"]], chance:5, source:"Forestry" },
  { id:"Лайм дикий", parents:[["сакуры", "лимонного дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Лайм пальчиковый", parents:[["Лайм дикий", "лимонного дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Помело", parents:[["сакуры", "лимонного дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Мандарин", parents:[["Помело", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Цитрон", parents:[["Помело", "лимонного дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Кумкват", parents:[["Мандарин", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Апельсин", parents:[["Помело", "Мандарин"]], chance:10, source:"ExtraTrees" },
  { id:"Цитрон пальчатый", parents:[["Цитрон", "Мандарин"]], chance:10, source:"ExtraTrees" },
  { id:"Танжерин", parents:[["Кумкват", "Мандарин"]], chance:10, source:"ExtraTrees" },
  { id:"Мандарин уншиу", parents:[["Кумкват", "Мандарин"]], chance:10, source:"ExtraTrees" },
  { id:"Грейпфрут", parents:[["Помело", "Апельсин"]], chance:10, source:"ExtraTrees" },
  { id:"Лайм", parents:[["Помело", "Лайм дикий"]], chance:10, source:"ExtraTrees" },
  { id:"Яблоня садовая", parents:[["яблочного дуба", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Яблоня венечная", parents:[["Яблоня садовая", "сахарного клёна"]], chance:10, source:"ExtraTrees" },
  { id:"Яблоня замечательная", parents:[["Яблоня садовая", "Яблоня венечная"]], chance:10, source:"ExtraTrees" },
  { id:"Яблоня айовская", parents:[["Яблоня садовая", "белой берёзы"]], chance:10, source:"ExtraTrees" },
  { id:"Терновник", parents:[["сливового дерева", "Яблоня садовая"]], chance:10, source:"ExtraTrees" },
  { id:"Алыча", parents:[["сливового дерева", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Персик", parents:[["сливового дерева", "каштана посевного"]], chance:10, source:"ExtraTrees" },
  { id:"Нектарин", parents:[["сливового дерева", "Персик"]], chance:10, source:"ExtraTrees" },
  { id:"Абрикос", parents:[["сливового дерева", "Персик"]], chance:10, source:"ExtraTrees" },
  { id:"Миндаль", parents:[["сливового дерева", "обычного орехового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Вишня дикая", parents:[["липы пушистой", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Вишня кислая", parents:[["белой ивы", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Черёмуха поздняя", parents:[["мирта", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Банан", parents:[["бальзы", "дерева джунглей"]], chance:10, source:"ExtraTrees" },
  { id:"Красный банан", parents:[["Банан", "хлопкового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Плантан", parents:[["Банан", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Бук европейский", parents:[["белой берёзы", "яблочного дуба"]], chance:10, source:"ExtraTrees" },
  { id:"Ольха чёрная", parents:[["белой берёзы", "Бук европейский"]], chance:10, source:"ExtraTrees" },
  { id:"Осина", parents:[["Ольха чёрная", "Бук европейский"]], chance:10, source:"ExtraTrees" },
  { id:"Рябина обыкновенная", parents:[["Осина", "Ольха чёрная"]], chance:10, source:"ExtraTrees" },
  { id:"Лещина обыкновенная", parents:[["Бук европейский", "Осина"]], chance:10, source:"ExtraTrees" },
  { id:"Боярышник однопестичный", parents:[["Бук европейский", "Рябина обыкновенная"]], chance:10, source:"ExtraTrees" },
  { id:"Бузина", parents:[["Ольха чёрная", "Осина"]], chance:10, source:"ExtraTrees" },
  { id:"Остролист обыкновенный", parents:[["Ольха чёрная", "Рябина обыкновенная"]], chance:10, source:"ExtraTrees" },
  { id:"Ива козья", parents:[["белой ивы", "Осина"]], chance:10, source:"ExtraTrees" },
  { id:"Пекан обыкновенный", parents:[["Бук европейский", "белой берёзы"]], chance:10, source:"ExtraTrees" },
  { id:"Бук медный", parents:[["Бук европейский", "красной ели"]], chance:10, source:"ExtraTrees" },
  { id:"Ясень обыкновенный", parents:[["липы пушистой", "красной ели"]], chance:10, source:"ExtraTrees" },
  { id:"Рябина круглолистная", parents:[["Ясень обыкновенный", "белой берёзы"]], chance:10, source:"ExtraTrees" },
  { id:"Вяз обыкновенный", parents:[["Ясень обыкновенный", "жёлтой сосны"]], chance:10, source:"ExtraTrees" },
  { id:"Граб обыкновенный", parents:[["Ясень обыкновенный", "мировой лиственницы"]], chance:10, source:"ExtraTrees" },
  { id:"Сикомор", parents:[["Ясень обыкновенный", "сахарного клёна"]], chance:10, source:"ExtraTrees" },
  { id:"Тис ягодный", parents:[["мировой лиственницы", "красной ели"]], chance:10, source:"ExtraTrees" },
  { id:"Пихта бальзамическая", parents:[["мировой лиственницы", "Ольха чёрная"]], chance:10, source:"ExtraTrees" },
  { id:"Пихта белая", parents:[["жёлтой сосны", "Пихта бальзамическая"]], chance:10, source:"ExtraTrees" },
  { id:"Тсуга западная", parents:[["жёлтой сосны", "Пихта белая"]], chance:10, source:"ExtraTrees", cond:"мин. высота 80" },
  { id:"Кедр", parents:[["Пихта белая", "мировой лиственницы"]], chance:10, source:"ExtraTrees", cond:"мин. высота 60" },
  { id:"Пихта Дугласа", parents:[["Пихта белая", "красной ели"]], chance:10, source:"ExtraTrees", cond:"мин. высота 60" },
  { id:"Кипарисовик Лавсона", parents:[["жёлтой сосны", "красной ели"]], chance:10, source:"ExtraTrees" },
  { id:"Сосна Лоблолли", parents:[["жёлтой сосны", "красной ели"]], chance:10, source:"ExtraTrees" },
  { id:"Орех серый", parents:[["обычного орехового дерева", "сакуры"]], chance:10, source:"ExtraTrees" },
  { id:"Дуб черешчатый", parents:[["обычного орехового дерева", "яблочного дуба"]], chance:10, source:"ExtraTrees" },
  { id:"Олива", parents:[["сакуры", "Ольха чёрная"]], chance:10, source:"ExtraTrees" },
  { id:"Клён красный", parents:[["сахарного клёна", "липы пушистой"]], chance:10, source:"ExtraTrees" },
  { id:"Ликвидамбар смолоносный", parents:[["сахарного клёна", "мировой лиственницы"]], chance:10, source:"ExtraTrees" },
  { id:"Робиния ложноакациевая", parents:[["бальзы", "липы пушистой"]], chance:10, source:"ExtraTrees" },
  { id:"Ироко", parents:[["бальзы", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Груша садовая", parents:[["Яблоня садовая", "белой берёзы"]], chance:10, source:"ExtraTrees" },
  { id:"Маклюра красильная", parents:[["мирта", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Маклюра оранжевая", parents:[["Маклюра красильная", "хлопкового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Цезальпиния ежовая", parents:[["мирта", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Амарант", parents:[["Цезальпиния ежовая", "хлопкового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Розовое дерево", parents:[["мирта", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Кампешевое дерево", parents:[["Розовое дерево", "хлопкового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Гинкго двулопастный", parents:[["дерева Венге", "липы пушистой"]], chance:10, source:"ExtraTrees" },
  { id:"Бразильский орех", parents:[["Бук европейский", "дерева джунглей"]], chance:10, source:"ExtraTrees" },
  { id:"Эвкалипт гигантский", parents:[["бальзы", "дерева джунглей"]], chance:10, source:"ExtraTrees" },
  { id:"Эвкалипт болотный", parents:[["Эвкалипт гигантский", "жёлтого меранти"]], chance:10, source:"ExtraTrees" },
  { id:"Гвоздичное дерево", parents:[["Кофейное дерево", "тикового дерева"]], chance:10, source:"ExtraTrees" },
  { id:"Кофейное дерево", parents:[["сакуры", "дерева джунглей"]], chance:10, source:"ExtraTrees" },
  { id:"Самшит вечнозелёный", parents:[["Остролист обыкновенный", "Ольха чёрная"]], chance:10, source:"ExtraTrees" },
  { id:"Араукария чилийская", parents:[["Тсуга западная", "дерева джунглей"]], chance:10, source:"ExtraTrees" },
  { id:"Эвкалипт радужный", parents:[["Эвкалипт гигантский", "бальзы"]], chance:10, source:"ExtraTrees" },
  { id:"Умнини (розовая кость)", parents:[["Эвкалипт гигантский", "Цезальпиния ежовая"]], chance:10, source:"ExtraTrees" },
  { id:"Малина", parents:[["сакуры", "Бузина"]], chance:10, source:"ExtraTrees" },
  { id:"Смородина красная", parents:[["сакуры", "Бузина"]], chance:10, source:"ExtraTrees" },
  { id:"Смородина чёрная", parents:[["Черёмуха поздняя", "Смородина красная"]], chance:10, source:"ExtraTrees" },
  { id:"Ежевика", parents:[["Черёмуха поздняя", "Малина"]], chance:10, source:"ExtraTrees" },
  { id:"Голубика", parents:[["Ежевика", "Малина"]], chance:10, source:"ExtraTrees" },
  { id:"Клюква", parents:[["Ежевика", "Алыча"]], chance:10, source:"ExtraTrees" },
  { id:"Можжевельник", parents:[["Малина", "Пихта белая"]], chance:10, source:"ExtraTrees" },
  { id:"Крыжовник", parents:[["Малина", "Лайм"]], chance:10, source:"ExtraTrees" },
  { id:"Малина золотая", parents:[["Малина", "Апельсин"]], chance:10, source:"ExtraTrees" },
  { id:"Коричник цейлонский", parents:[["тикового дерева", "Розовое дерево"]], chance:10, source:"ExtraTrees" },
  { id:"Кокосовая пальма", parents:[["бальзы", "Бразильский орех"]], chance:10, source:"ExtraTrees" },
  { id:"Кешью", parents:[["тикового дерева", "яблочного дуба"]], chance:10, source:"ExtraTrees" },
  { id:"Авокадо", parents:[["дерева Венге", "яблочного дуба"]], chance:10, source:"ExtraTrees" },
  { id:"Мускатный орех", parents:[["тикового дерева", "Гвоздичное дерево"]], chance:10, source:"ExtraTrees" },
  { id:"Перец душистый", parents:[["тикового дерева", "Гвоздичное дерево"]], chance:10, source:"ExtraTrees" },
  { id:"Анис звёздчатый", parents:[["Перец душистый", "Гвоздичное дерево"]], chance:10, source:"ExtraTrees" },
  { id:"Манго", parents:[["дерева джунглей", "Апельсин"]], chance:10, source:"ExtraTrees" },
  { id:"Карамбола", parents:[["Анис звёздчатый", "Манго"]], chance:10, source:"ExtraTrees" },
  { id:"Лумбанг (свечное дерево)", parents:[["Лещина обыкновенная", "Гинкго двулопастный"]], chance:10, source:"ExtraTrees" },
  { id:"Перец красный", parents:[["Лещина обыкновенная", "Гинкго двулопастный"]], chance:10, source:"ExtraTrees" },
  { id:"Лещина карликовая", parents:[["Лещина обыкновенная", "Ольха чёрная"]], chance:10, source:"ExtraTrees" },
];